### ISSUE TITLE
EAB presentation

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#27]
### Provide a description

@AidaMehonic to give 5 minute RAM presentation of wider TPS presentation at EAB 5/12/22 12:30 - 12:50

## Tasks

- [x] Create EAB presentation
- [x] Feedback on EAB presentation
- [x] Practice (at coworking 2/12/22)

## Links
[Slide deck](https://docs.google.com/presentation/d/1KwiDFrxHNc2tNBQqMT1lM7nF20vBQWbu/edit#slide=id.p2)

**Comment by harisood** [comment]
Presentation given!
