### ISSUE TITLE
Pitchfest at AIUK 2023

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#28]
## Summary

@harisood & @aldenc to lead on the development of pitchfest for AI UK

## Tasks
- [x] Arrange a meeting with partnerships to discuss possible judges - @aldenc 
- [x] Formulate one-pager - @harisood 
- [ ] Finalise judges
- [ ] Finalise everything to open applications

## Useful Links
- x
-

**Comment by harisood** [comment]
Provisional timeline: 

* Open applications: 9th Jan
* Close applications: 10th February
* Decision made on finalists: 24th February
* Training sessions for Pitchfest: w/c 27th Feb, 6th March
* Rehearsal in Enigma (for internal staff) – 13th or 14th March
